server:
  port: 8088

spring:
  messages:
    basename: messages
  # security:
  #   user:
  #     name: username
  #     password: passw0rd

management:
  endpoints:
    web:
      exposure:
        include: "*"


#logging:
#  level:
#    org:
#      springframework: debug
